"""admin assignment audit time-tracking

Revision ID: 27e0fffb1a1d
Revises: 98a128af89d5
Create Date: 2026-06-17 19:30:00.000000

Hand-authored migration (not autogenerated). Adds role/capacity to users;
assignment, dedup, versioning and lead_number columns to leads; and three new
tables: audit_events (append-only), lead_state_periods (time tracking), and
app_settings (single-row global config).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "27e0fffb1a1d"
down_revision: Union[str, None] = "98a128af89d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- users: role + capacity ---------------------------------------------
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.String(length=50),
            server_default="ATTORNEY",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "max_open_cases",
            sa.Integer(),
            server_default="20",
            nullable=False,
        ),
    )

    # --- leads: new columns -------------------------------------------------
    op.add_column("leads", sa.Column("lead_number", sa.String(length=50), nullable=True))
    op.add_column(
        "leads", sa.Column("normalized_email", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "leads", sa.Column("assignee_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "leads",
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column(
        "leads", sa.Column("submitter_ip", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "leads", sa.Column("idempotency_key", sa.String(length=255), nullable=True)
    )
    op.add_column("leads", sa.Column("duplicate_of", sa.UUID(), nullable=True))
    op.add_column(
        "leads",
        sa.Column(
            "is_potential_duplicate",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )

    op.create_index(
        op.f("ix_leads_normalized_email"),
        "leads",
        ["normalized_email"],
        unique=False,
    )
    op.create_unique_constraint("uq_leads_lead_number", "leads", ["lead_number"])
    op.create_unique_constraint(
        "uq_leads_idempotency_key", "leads", ["idempotency_key"]
    )
    op.create_foreign_key(
        "fk_leads_assignee_id_users",
        "leads",
        "users",
        ["assignee_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_leads_duplicate_of_leads",
        "leads",
        "leads",
        ["duplicate_of"],
        ["id"],
        ondelete="SET NULL",
    )

    # --- audit_events (append-only) -----------------------------------------
    op.create_table(
        "audit_events",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_kind", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_lead_id"), "audit_events", ["lead_id"], unique=False
    )

    # --- lead_state_periods (time tracking) ---------------------------------
    op.create_table(
        "lead_state_periods",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.Column("assignee_id", sa.UUID(), nullable=True),
        sa.Column(
            "entered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("exited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["assignee_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lead_state_periods_lead_id"),
        "lead_state_periods",
        ["lead_id"],
        unique=False,
    )

    # --- app_settings (single row) ------------------------------------------
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column(
            "auto_assign_enabled",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        "INSERT INTO app_settings (id, auto_assign_enabled) VALUES (1, true)"
    )


def downgrade() -> None:
    op.drop_table("app_settings")

    op.drop_index(
        op.f("ix_lead_state_periods_lead_id"), table_name="lead_state_periods"
    )
    op.drop_table("lead_state_periods")

    op.drop_index(op.f("ix_audit_events_lead_id"), table_name="audit_events")
    op.drop_table("audit_events")

    op.drop_constraint("fk_leads_duplicate_of_leads", "leads", type_="foreignkey")
    op.drop_constraint("fk_leads_assignee_id_users", "leads", type_="foreignkey")
    op.drop_constraint("uq_leads_idempotency_key", "leads", type_="unique")
    op.drop_constraint("uq_leads_lead_number", "leads", type_="unique")
    op.drop_index(op.f("ix_leads_normalized_email"), table_name="leads")

    op.drop_column("leads", "is_potential_duplicate")
    op.drop_column("leads", "duplicate_of")
    op.drop_column("leads", "idempotency_key")
    op.drop_column("leads", "submitter_ip")
    op.drop_column("leads", "version")
    op.drop_column("leads", "assignee_id")
    op.drop_column("leads", "normalized_email")
    op.drop_column("leads", "lead_number")

    op.drop_column("users", "max_open_cases")
    op.drop_column("users", "role")
